spring:
  application:
    name: Config-Default  # Application name
eureka:
  instance:
    hostname: localhost  # Hostname
  client:
      registerWithEureka: true  # Register with Eureka
      fetchRegistry: true  # Fetch the registry
      serviceUrl:
          defaultZone: http://localhost:8761/eureka/  # Eureka server URL